[project]
name = "ai-agent-nl2sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YahiaAbdalla2712", email = "yayaabdalla2712@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "docker>=7.2.0",
    "dockerclient>=0.0.0",
    "langchain>=1.4.2",
    "langchain-ollama>=1.1.0",
    "pydantic>=2.13.5",
    "pyodbc>=5.3.0",
    "qdrant-client>=1.19.1",
]

[project.scripts]
ai-agent-nl2sql = "ai_agent_nl2sql:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
